# Atalho para criar POST: mptr
# Atalho CTRL + J para ver todas as opções possíveis

@Host = http://localhost:3000
@BearerToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudGUyQGVtYWlsLmNvbSIsIm5hbWVpZCI6IjJkOWY4YWIzLWNhOTItNDVhMy1iYzUxLTNjZjk3ZjllZmUxMCIsIkNwZiI6IjAwMDExMTIyMjMzIiwiTmFtZSI6IkNsaWVudGUgMiIsIm5iZiI6MTcyMjY1MTk0NCwiZXhwIjoxNzU0MTg3OTQ0LCJpYXQiOjE3MjI2NTE5NDQsImlzcyI6IklXYW50QXBwSXNzdWVyIiwiYXVkIjoiQXVkaWVuY2UifQ.65M2CQrnxeIg9YhylKr5UsgKdKRQMqKuapNFioYW4Mk

GET {{ Host }}/categories
Accept: application/json
Authorization: {{ BearerToken }}

###

POST {{ Host }}/categories
Content-Type: application/json
Authorization: {{ BearerToken }}

{
  "name": "Food 3"
}

###

PUT {{ Host }}/categories/8dd4785a-579a-4c74-96a8-9708634a73ba
Content-Type: application/json
Authorization: {{ BearerToken }}

{
  "name": "Food 3 - EDITED",
  "active": false
}

###

POST {{ Host }}/employees
Content-Type: application/json
Authorization: {{ BearerToken }}

{
  "Name": "User 12",
  "Email": "user12@gmail.com",
  "Password": "12345678",
  "EmployeeCode": "012"
}

###

GET {{ Host }}/employees?page=1&rows=10
Accept: application/json
Authorization: {{BearerToken}}

###

POST {{ Host }}/token
Content-Type: application/json

{
  "email": "cliente2@email.com",
  "password": "12345678"
}

###

POST {{ Host }}/products
Content-Type: application/json
Authorization: {{ BearerToken }}

{
  "name": "Produto 7",
  "description": "melhor produto 7",
  "categoryId": "abbb0f67-666c-4fe0-bc60-f276c7dcd3ed",
  "hasStock": true,
  "price": 70.3
}

###

GET {{ Host }}/products
Accept: application/json
Authorization: {{ BearerToken }}

###

GET {{ Host }}/products/showcase?page=1&row=10&orderBy=price
Accept: application/json
Authorization: {{ BearerToken }}

###

POST {{ Host }}/clients
Content-Type: application/json

{
  "email": "cliente2@email.com",
  "name": "Cliente 2",
  "password": "12345678",
  "cpf": "00011122233"
}

###

GET {{ Host }}/clients
Accept: application/json
Authorization: {{ BearerToken }}

###
