# Atalho para criar POST: mptr
# Atalho CTRL + J para ver todas as opções possíveis

@Host = http://localhost:3000
@Token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXI4QGdtYWlsLmNvbSIsIm5hbWVpZCI6IjNjYzFmYzIzLWE0ODktNDg4Mi1hNGRjLWZlYTU3YzNiYzQ2MiIsIkVtcGxveWVlQ29kZSI6IjAwOCIsIk5hbWUiOiJVc2VyIDgiLCJuYmYiOjE3MjIyMDQyMDgsImV4cCI6MTcyMjIwNzgwOCwiaWF0IjoxNzIyMjA0MjA4LCJpc3MiOiJJV2FudEFwcElzc3VlciIsImF1ZCI6IkF1ZGllbmNlIn0.Cs26efGwipUD09ckT-IyFpXSE-8MG4-pi1FOOAErG4I

GET {{ Host }}/categories
Accept: application/json
Authorization: {{ Token }}

###

POST {{ Host }}/categories
Content-Type: application/json
Authorization: {{ Token }}

{
  "name": "Food"
}

###

PUT {{ Host }}/categories/83112338-142a-46c5-9bef-fead1a2e62aa
Content-Type: application/json

{
  "name": "Clothes-update",
  "active": true
}

###

POST {{ Host }}/employees
Content-Type: application/json
Authorization: {{Token}}

{
  "Name": "User 9",
  "Email": "user9@gmail.com",
  "Password": "12345678",
  "EmployeeCode": "008"
}

###

GET {{ Host }}/employees?page=2&rows=5
Accept: application/json
Authorization: {{Token}}

###

POST {{ Host }}/token
Content-Type: application/json

{
  "email": "user8@gmail.com",
  "password": "12345678"
}

###
